---
# This file is maintained by avd_sync.py script.
# Port profiles may be edited manually, but servers will be overwritten on next run.
port_profiles:
  TENANT_A_CORE_L2VLANS:
    mode: trunk
    vlans: "10,11"
    spanning_tree_portfast: edge
  # TENANT_B_2020:
  #   mode: trunk
  #   vlans: 2020
  #   spanning_tree_portfast: edge
cpes:
  CPE1_SITE1_DUALHOMED:
    adapters:
    - endpoint_ports:
      - Ethernet4
      - Ethernet5
      switch_ports:
      - Ethernet3
      - Ethernet3
      switches:
      - PE-1A
      - PE-1B
      profile: TENANT_A_CORE_L2VLANS
      port_channel:
        description: EVPN-A-A-PortChannel
        mode: active
        short_esi: 0101:0303:0405
    rack: Undefined

  CPE4_SITE4_DUALHOMED:
    adapters:
    - endpoint_ports:
      - Ethernet4
      - Ethernet5
      switch_ports:
      - Ethernet3
      - Ethernet3
      switches:
      - PE-4A
      - PE-4B
      profile: TENANT_A_CORE_L2VLANS
      port_channel:
        description: EVPN-A-A-PortChannel
        mode: active
        short_esi: 0404:0303:0405
    rack: Undefined

