---
# This file is maintained by avd_sync.py script.
# Port profiles may be edited manually, but servers will be overwritten on next run.
port_profiles:
  TENANT_A_CORE_MULTIHOMED:
    mode: trunk
    vlans: "144"
    spanning_tree_portfast: edge
  TENANT_A_VXLAN:
    mode: trunk
    vlans: "231,232"
    spanning_tree_portfast: edge
cpes:
  CPE1_SITE1_DUALHOMED:
    adapters:
    - endpoint_ports:
      - Ethernet4
      - Ethernet5
      switch_ports:
      - Ethernet3
      - Ethernet3
      switches:
      - PE-1A
      - PE-1B
      profile: TENANT_A_CORE_MULTIHOMED
      port_channel:
        description: EVPN-A-A-PortChannel
        mode: active
        short_esi: 0101:0303:0405
    rack: Undefined

  CPE4_SITE4_DUALHOMED:
    adapters:
    - endpoint_ports:
      - Ethernet4
      - Ethernet5
      switch_ports:
      - Ethernet3
      - Ethernet3
      switches:
      - PE-4A
      - PE-4B
      profile: TENANT_A_CORE_MULTIHOMED
      port_channel:
        description: EVPN-A-A-PortChannel
        mode: active
        short_esi: 0404:0303:0405
    rack: Undefined

  CPE5_VXLAN:
    adapters:
    - endpoint_ports:
      - Ethernet1
      switch_ports:
      - Ethernet3
      switches:
      - SPE5
      profile: TENANT_A_VXLAN


  CPE6_VXLAN:
    adapters:
    - endpoint_ports:
      - Ethernet1
      switch_ports:
      - Ethernet3
      switches:
      - SPE6
      profile: TENANT_A_VXLAN