---
tenants:
  TENANT_A:
    mac_vrf_id_base: 10000
    pseudowire_rt_base: 1000
    l2vlans:
      144:
        name: TENANT_A_L2_SERVICE_144
        tags:
          - site1
          - site4
    point_to_point_services:
      # p2p pseudowire, vlan-based, 1 subinterface
      - name: TEN_A_site2_site5_eline_vlan_based
        type: vpws-pseudowire
        subinterfaces:
          - number: 21
        endpoints:
          - id: 2300
            nodes: ["PE-2"]
            interfaces: ["Ethernet3"]
          - id: 3300
            nodes: ["PE-3"]
            interfaces: ["Ethernet3"]
    vrfs:
      TENANT_A_L3VPN:
        vrf_id: 10
        address_families:
          - vpn-ipv4
        l3_interfaces:
          - description: TENANT_A_SITE_2_L3VPN
            enabled: true
            interfaces:
            - Ethernet3.22
            ip_addresses:
            - 23.23.102.1/24
            nodes:
            - PE-2
          - description: TENANT_A_SITE_3_L3VPN
            enabled: true
            interfaces:
            - Ethernet3.22
            ip_addresses:
            - 23.23.202.1/24
            nodes:
            - PE-3
        svis:
          231:
            enabled: true
            name: TENANT_A_VXLAN_231
            ip_address_virtual: 23.23.10.1/24
            tags:
              - vxlan-site5
              - vxlan-site6
          232:
            enabled: true
            name: TENANT_A_VXLAN_232
            ip_address_virtual: 23.23.20.1/24
            tags:
              - vxlan-site5
              - vxlan-site6

#   TENANT_B:
#     pseudowire_rt_base: 2000
#     mac_vrf_id_base: 20000
#     vrfs:
#       TENANT_B_INTRA:
#         vrf_id: 19
#         address_families:
#           - vpn-ipv4
#           - vpn-ipv6
#         ospf:
#           enabled: true
#           # process_id: 19 - Should default to vrf rt number
#           router_id: 123.1.1.0
#           max_lsa: 10000
#           nodes:
#             - pe3
#         l3_interfaces:
#           - description: TENANT_B_SITE_3_INTRA_L3VPN
#             enabled: true
#             interfaces:
#             - Ethernet6.10
#             ip_addresses:
#             - 123.1.1.0/31
#             nodes:
#             - pe3
#             ospf:
#               enabled: true
#               point_to_point: true
#               area: 0
#               cost: 10
#           - description: TENANT_B_SITE_5_INTRA_L3VPN
#             enabled: true
#             interfaces:
#             - Ethernet6.10
#             ip_addresses:
#             - 123.1.1.2/31
#             nodes:
#             - pe5
#         static_routes:
#           - destination_address_prefix: 123.0.10.0/24
#             gateway: 123.1.1.3
#             name: TENANT_B_SITE_5_SUBNET
#             interface: Ethernet6.10
#             nodes:
#               - pe5
#         svis:
#           2020:
#             enabled: true
#             name: TENANT_B_INSIDE_FW
#             ip_virtual_router_addresses: [10.1.255.1]
#             nodes:
#               pe1:
#                 ip_address: 10.1.255.2/27
#               pe2:
#                 ip_address: 10.1.255.3/27
#             tags:
#               - site1-2
#         bgp_peers:
#           10.1.255.4:
#             description: TENANT_B_CPE_SITE3
#             # ebgp_multihop: 1
#             nodes:
#             - pe1
#             - pe2
#             password: $1c$U4tL2vQP9QwZlxIV1K3/pw==
#             remote_as: "12345"
#             set_ipv4_next_hop: 10.1.255.1

#       INTERNET:
#         vrf_id: 19
#         address_families:
#           - evpn
#         l3_interfaces:
#           - description: TENANT_B_SITE_3_INTRA_L3VPN
#             enabled: true
#             interfaces:
#             - Ethernet21/1
#             ip_addresses:
#             - 172.16.3.0/31
#             nodes:
#             - pe1
#         bgp_peers:
#           172.16.3.1 :
#             description: TENANT_B_CPE_SITE3
#             # ebgp_multihop: 1
#             nodes:
#             - pe1
#             remote_as: "65501"
#             maximum_routes: 0
#             default_originate: true

#       TENANT_B_WAN:
#         vrf_id: 20
#         address_families:
#           - vpn-ipv4
#         # redistribute_ospf: true should default to true if there is ospf defined in the vrf.
#           # nodes:
#         ospf:
#           enabled: true
#           process_id: 99      # defaults to vrf RT number
#           router_id: 192.168.48.4  # defaults to switch.router_id
#           # bfd: true           # implicit default is false
#           max_lsa: 10000      # omitted if not defined
#           nodes:
#             - pe3
#         l3_interfaces:
#         - description: TENANT_B_SITE_3
#           enabled: true
#           interfaces:
#           - Ethernet5.100
#           ip_addresses:
#           - 192.168.48.0/31
#           nodes:
#           - pe3
#           # bgp_peers:
#           #   192.168.48.1:
#           #     remote_as: 65123

#         - description: TENANT_B_SITE_3_OSPF
#           enabled: true
#           interfaces:
#           - Ethernet6.100
#           ip_addresses:
#           - 192.168.48.4/31
#           nodes:
#           - pe3
#           ospf:
#             enabled: true
#             point_to_point: true
#             area: 0
#             cost: 10
#             # autentication: "simple"
#             # simple_auth_key: "something"
#         - description: TENANT_B_SITE_5
#           enabled: true
#           interfaces:
#           - Ethernet6.10
#           ip_addresses:
#           - 192.168.48.2/31
#           nodes:
#           - pe5
#         bgp_peers:
#           192.168.48.1:
#             description: TENANT_B_CPE_SITE3
#             # ebgp_multihop: 1
#             nodes:
#             - pe3
#             password: $1c$U4tL2vQP9QwZlxIV1K3/pw==
#             remote_as: "65201"
#             # send_community: all
#             # set_ipv4_next_hop: 123.123.123.1
#             # route_map:
#           192.168.48.3:
#             description: TENANT_B_CPE_SITE5
#             # ebgp_multihop: 1
#             nodes:
#             - pe5
#             password: $1c$U4tL2vQP9QwZlxIV1K3/pw==
#             remote_as: "65202"
#             # send_community: all
