---
tenants:
  TENANT_A:
    mac_vrf_id_base: 10000
    pseudowire_rt_base: 1000
    l2vlans:
      144:
        name: TENANT_A_L2_SERVICE_144
        tags:
          - site1
          - site4
    point_to_point_services:
      # p2p pseudowire, vlan-based, 1 subinterface
      - name: TEN_A_site2_site5_eline_vlan_based
        type: vpws-pseudowire
        subinterfaces:
          - number: 21
        endpoints:
          - id: 2300
            nodes: ["PE-2"]
            interfaces: ["Ethernet3"]
          - id: 3300
            nodes: ["PE-3"]
            interfaces: ["Ethernet3"]
    vrfs:
      TENANT_A_L3VPN:
        vrf_id: 10
        address_families:
          - vpn-ipv4
        l3_interfaces:
          - description: TENANT_A_SITE_2_L3VPN
            enabled: true
            interfaces:
            - Ethernet3.22
            ip_addresses:
            - 23.23.102.1/24
            nodes:
            - PE-2
          - description: TENANT_A_SITE_3_L3VPN
            enabled: true
            interfaces:
            - Ethernet3.22
            ip_addresses:
            - 23.23.202.1/24
            nodes:
            - PE-3
        svis:
          231:
            enabled: true
            name: TENANT_A_VXLAN_231
            ip_address_virtual: 23.23.10.1/24
            tags:
              - vxlan-site5
              - vxlan-site6
          232:
            enabled: true
            name: TENANT_A_VXLAN_232
            ip_address_virtual: 23.23.20.1/24
            tags:
              - vxlan-site5
              - vxlan-site6
