---
- name: Build Switch configuration
  hosts: VXLAN_NETWORK
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: generate intended variables
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_cli_config_gen
      when: structured_config.changed

- name: Build Switch configuration
  hosts: MPLS_NETWORK
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: generate intended variables
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_cli_config_gen
      when: structured_config.changed

# - name: Configuration deployment with CVP
#   hosts: cv_server
#   connection: local
#   gather_facts: false
#   tasks:
#     - name: run CVP provisioning
#       import_role:
#         name: arista.avd.eos_config_deploy_cvp
#       vars:
#         container_root: 'ALL_NODES'
#         configlets_prefix: 'POC-AVD'
#         # execute_tasks: true
#         search_key: hostname
#         state: present
#         cv_collection: v3
#         apply_mode: loose
