---
- name: Build and deploy switch configuration for VXLAN_NETWORK
  hosts: VXLAN_NETWORK
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: generate intended variables
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_cli_config_gen
      when: structured_config.changed

    - name: deploy configuration to devices
      tags: [deploy, never]
      import_role:
        name: arista.avd.eos_config_deploy_eapi
      # when: eosconfig.changed

- name: Build and deploy switch configuration for MPLS_NETWORK
  hosts: MPLS_NETWORK
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: generate intended variables
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_cli_config_gen
      when: structured_config.changed

    - name: deploy configuration to devices
      tags: [deploy, never]
      import_role:
        name: arista.avd.eos_config_deploy_eapi
      # when: eosconfig.changed
